
all:
	gcc -O -o Elast_Solver.out Elast_Solver.cpp -L/home/jiraseka/Cprogs/lsipdx/Source -llsipdx -Wl,-rpath=/home/jiraseka/Cprogs/lsipdx/Source  -L/home/jiraseka/Cprogs/libm3l/data_util/Source -lm3l -Wl,-rpath=/home/jiraseka/Cprogs/libm3l/data_util/Source -lpthread -lm

 
